version: '3'

services:
  app:
    build:
      context: .
    container_name: user_app_spring
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/userDb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    ports:
      - '8080:8080'

  db:
    image: postgres:13.3
    container_name: user_db_postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=userDb
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d